# Generated by Django 3.2.9 on 2022-02-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_auto_20220131_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default='22/01/31'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(default='18/19'),
        ),
    ]
