# Generated by Django 3.2.9 on 2022-02-01 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_auto_20220131_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.TimeField(default=datetime.time),
        ),
    ]
