# Generated by Django 3.2.9 on 2022-02-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_task_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
